on: [pull_request]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Copy labels from linked issues
    steps:
      - name: copy-labels
        uses: michalvankodev/copy-issue-labels@v0.2.12
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
